
import type { PontoResfriamento } from '@/services/supabaseService';

export const additionalPontos: PontoResfriamento[] = [
  // Zona Norte
  {
    id: '7',
    nome: 'Parque da Juventude',
    descricao: 'Grande parque com áreas verdes e equipamentos de lazer.',
    tipo: 'parque',
    latitude: -23.5162,
    longitude: -46.6278,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '8',
    nome: 'Shopping Center Norte',
    descricao: 'Shopping com ar-condicionado e praça de alimentação.',
    tipo: 'abrigo',
    latitude: -23.5113,
    longitude: -46.6177,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '9',
    nome: 'Biblioteca de São Paulo',
    descricao: 'Biblioteca climatizada com espaços de leitura.',
    tipo: 'abrigo',
    latitude: -23.5163,
    longitude: -46.6210,
    horario_funcionamento: '08:00 - 17:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '10',
    nome: 'Estação Tucuruvi',
    descricao: 'Estação de metrô climatizada.',
    tipo: 'abrigo',
    latitude: -23.4798,
    longitude: -46.6037,
    horario_funcionamento: '04:40 - 00:40',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '11',
    nome: 'Parque Linear Engenheiro Werner Zulauf',
    descricao: 'Parque linear com trilhas e áreas sombreadas.',
    tipo: 'parque',
    latitude: -23.4923,
    longitude: -46.6234,
    horario_funcionamento: '06:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },

  // Zona Sul
  {
    id: '12',
    nome: 'Parque do Estado',
    descricao: 'Amplo parque com jardim botânico e zoológico.',
    tipo: 'parque',
    latitude: -23.6391,
    longitude: -46.6216,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '13',
    nome: 'Shopping Interlagos',
    descricao: 'Centro comercial climatizado na Zona Sul.',
    tipo: 'abrigo',
    latitude: -23.6764,
    longitude: -46.6917,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '14',
    nome: 'CEU Butantã',
    descricao: 'Centro educacional com biblioteca e teatro climatizados.',
    tipo: 'abrigo',
    latitude: -23.5771,
    longitude: -46.7247,
    horario_funcionamento: '07:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '15',
    nome: 'Parque Burle Marx',
    descricao: 'Parque com extensa área verde e trilhas.',
    tipo: 'parque',
    latitude: -23.6326,
    longitude: -46.7048,
    horario_funcionamento: '05:00 - 19:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '16',
    nome: 'Terminal Jabaquara',
    descricao: 'Terminal rodoviário com área climatizada.',
    tipo: 'abrigo',
    latitude: -23.6363,
    longitude: -46.6435,
    horario_funcionamento: '24h',
    cidade: 'São Paulo',
    uf: 'SP',
  },

  // Zona Leste
  {
    id: '17',
    nome: 'Parque Ecológico do Tietê',
    descricao: 'Parque às margens do Rio Tietê com áreas sombreadas.',
    tipo: 'parque',
    latitude: -23.4891,
    longitude: -46.5203,
    horario_funcionamento: '06:00 - 17:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '18',
    nome: 'Shopping Aricanduva',
    descricao: 'Um dos maiores shoppings da América Latina.',
    tipo: 'abrigo',
    latitude: -23.5439,
    longitude: -46.4826,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '19',
    nome: 'CEU Azul da Cor do Mar',
    descricao: 'Centro educacional com equipamentos climatizados.',
    tipo: 'abrigo',
    latitude: -23.5697,
    longitude: -46.4741,
    horario_funcionamento: '07:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '20',
    nome: 'Parque Raul Seixas',
    descricao: 'Parque urbano com mata preservada.',
    tipo: 'parque',
    latitude: -23.5847,
    longitude: -46.4692,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '21',
    nome: 'Estação Corinthians-Itaquera',
    descricao: 'Estação de metrô e trem climatizada.',
    tipo: 'abrigo',
    latitude: -23.5441,
    longitude: -46.4734,
    horario_funcionamento: '04:40 - 00:40',
    cidade: 'São Paulo',
    uf: 'SP',
  },

  // Zona Oeste
  {
    id: '22',
    nome: 'Parque Villa-Lobos',
    descricao: 'Parque urbano com ciclovias e áreas de lazer.',
    tipo: 'parque',
    latitude: -23.5447,
    longitude: -46.7208,
    horario_funcionamento: '05:30 - 19:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '23',
    nome: 'Shopping Eldorado',
    descricao: 'Shopping center com ampla praça de alimentação.',
    tipo: 'abrigo',
    latitude: -23.5563,
    longitude: -46.6934,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '24',
    nome: 'CEAGESP',
    descricao: 'Central de abastecimento com áreas cobertas.',
    tipo: 'abrigo',
    latitude: -23.5631,
    longitude: -46.7339,
    horario_funcionamento: '08:00 - 17:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '25',
    nome: 'Parque Previdência',
    descricao: 'Parque com equipamentos de ginástica e playground.',
    tipo: 'parque',
    latitude: -23.5759,
    longitude: -46.7013,
    horario_funcionamento: '06:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '26',
    nome: 'Hospital das Clínicas - USP',
    descricao: 'Complexo hospitalar com áreas climatizadas públicas.',
    tipo: 'abrigo',
    latitude: -23.5567,
    longitude: -46.6723,
    horario_funcionamento: '24h',
    cidade: 'São Paulo',
    uf: 'SP',
  },

  // ABC Paulista
  {
    id: '27',
    nome: 'Parque Central Santo André',
    descricao: 'Grande parque urbano com lago e áreas verdes.',
    tipo: 'parque',
    latitude: -23.6540,
    longitude: -46.5307,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'Santo André',
    uf: 'SP',
  },
  {
    id: '28',
    nome: 'Shopping ABC',
    descricao: 'Centro comercial climatizado em Santo André.',
    tipo: 'abrigo',
    latitude: -23.6563,
    longitude: -46.5341,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'Santo André',
    uf: 'SP',
  },
  {
    id: '29',
    nome: 'Centro Cultural Fábrica',
    descricao: 'Espaço cultural climatizado com biblioteca.',
    tipo: 'abrigo',
    latitude: -23.6598,
    longitude: -46.5384,
    horario_funcionamento: '09:00 - 18:00',
    cidade: 'Santo André',
    uf: 'SP',
  },
  {
    id: '30',
    nome: 'Parque Cidade de Toronto',
    descricao: 'Parque com playground e quadras esportivas.',
    tipo: 'parque',
    latitude: -23.6186,
    longitude: -46.5432,
    horario_funcionamento: '06:00 - 22:00',
    cidade: 'São Caetano do Sul',
    uf: 'SP',
  },
  {
    id: '31',
    nome: 'Shopping São Caetano',
    descricao: 'Centro comercial com cinema e praça de alimentação.',
    tipo: 'abrigo',
    latitude: -23.6143,
    longitude: -46.5563,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Caetano do Sul',
    uf: 'SP',
  },

  // Grande São Paulo - Demais Municípios
  {
    id: '32',
    nome: 'Parque Municipal Guarulhos',
    descricao: 'Parque com bosque e trilhas ecológicas.',
    tipo: 'parque',
    latitude: -23.4628,
    longitude: -46.5333,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'Guarulhos',
    uf: 'SP',
  },
  {
    id: '33',
    nome: 'Shopping Internacional Guarulhos',
    descricao: 'Shopping climatizado próximo ao aeroporto.',
    tipo: 'abrigo',
    latitude: -23.4345,
    longitude: -46.4973,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'Guarulhos',
    uf: 'SP',
  },
  {
    id: '34',
    nome: 'Terminal Rodoviário de Osasco',
    descricao: 'Terminal com área de espera climatizada.',
    tipo: 'abrigo',
    latitude: -23.5329,
    longitude: -46.7918,
    horario_funcionamento: '05:00 - 00:00',
    cidade: 'Osasco',
    uf: 'SP',
  },
  {
    id: '35',
    nome: 'Parque Municipal Chico Mendes',
    descricao: 'Parque ecológico com mata atlântica preservada.',
    tipo: 'parque',
    latitude: -23.5247,
    longitude: -46.7654,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'Osasco',
    uf: 'SP',
  },
  {
    id: '36',
    nome: 'Centro Cultural de Diadema',
    descricao: 'Espaço cultural com teatro e biblioteca climatizados.',
    tipo: 'abrigo',
    latitude: -23.6859,
    longitude: -46.6109,
    horario_funcionamento: '08:00 - 20:00',
    cidade: 'Diadema',
    uf: 'SP',
  },
  {
    id: '37',
    nome: 'Parque Pinheirinho de Água',
    descricao: 'Parque linear com nascentes e áreas verdes.',
    tipo: 'parque',
    latitude: -23.6794,
    longitude: -46.6243,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'Diadema',
    uf: 'SP',
  },
  {
    id: '38',
    nome: 'Shopping Center Mauá',
    descricao: 'Centro comercial regional climatizado.',
    tipo: 'abrigo',
    latitude: -23.6677,
    longitude: -46.4615,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'Mauá',
    uf: 'SP',
  },
  {
    id: '39',
    nome: 'Parque Max Feffer',
    descricao: 'Parque ecológico com lago e trilhas.',
    tipo: 'parque',
    latitude: -23.6234,
    longitude: -46.4187,
    horario_funcionamento: '07:00 - 17:00',
    cidade: 'Suzano',
    uf: 'SP',
  },
  {
    id: '40',
    nome: 'Casa da Cultura Suzano',
    descricao: 'Espaço cultural climatizado com exposições.',
    tipo: 'abrigo',
    latitude: -23.5425,
    longitude: -46.3108,
    horario_funcionamento: '08:00 - 17:00',
    cidade: 'Suzano',
    uf: 'SP',
  },

  // Fontes e Bebedouros
  {
    id: '41',
    nome: 'Fonte da Praça Roosevelt',
    descricao: 'Fonte ornamental com bebedouros públicos.',
    tipo: 'fonte',
    latitude: -23.5444,
    longitude: -46.6434,
    horario_funcionamento: '24h',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '42',
    nome: 'Bebedouro Parque Augusta',
    descricao: 'Bebedouros públicos no parque urbano.',
    tipo: 'fonte',
    latitude: -23.5529,
    longitude: -46.6632,
    horario_funcionamento: '24h',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '43',
    nome: 'Fonte Memorial da América Latina',
    descricao: 'Complexo com fontes e bebedouros.',
    tipo: 'fonte',
    latitude: -23.5267,
    longitude: -46.6634,
    horario_funcionamento: '09:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '44',
    nome: 'Bebedouros Estação da Luz',
    descricao: 'Bebedouros na estação ferroviária histórica.',
    tipo: 'fonte',
    latitude: -23.5357,
    longitude: -46.6357,
    horario_funcionamento: '05:00 - 00:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '45',
    nome: 'Fonte Largo do Arouche',
    descricao: 'Fonte histórica com água potável.',
    tipo: 'fonte',
    latitude: -23.5441,
    longitude: -46.6443,
    horario_funcionamento: '24h',
    cidade: 'São Paulo',
    uf: 'SP',
  },

  // Pontos Adicionais Diversos
  {
    id: '46',
    nome: 'SESC Pompeia',
    descricao: 'Centro cultural e esportivo com ar-condicionado.',
    tipo: 'abrigo',
    latitude: -23.5288,
    longitude: -46.6917,
    horario_funcionamento: '09:00 - 21:30',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '47',
    nome: 'Instituto Butantan',
    descricao: 'Museu climatizado com parque anexo.',
    tipo: 'abrigo',
    latitude: -23.5667,
    longitude: -46.7081,
    horario_funcionamento: '09:00 - 16:45',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '48',
    nome: 'Mercado Municipal',
    descricao: 'Mercado histórico com áreas cobertas.',
    tipo: 'abrigo',
    latitude: -23.5473,
    longitude: -46.6334,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '49',
    nome: 'Parque Linear Ribeirão Colônia',
    descricao: 'Parque linear com ciclovia e áreas verdes.',
    tipo: 'parque',
    latitude: -23.7123,
    longitude: -46.6789,
    horario_funcionamento: '06:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '50',
    nome: 'Terminal Capelinha',
    descricao: 'Terminal de ônibus com área de espera climatizada.',
    tipo: 'abrigo',
    latitude: -23.5789,
    longitude: -46.7234,
    horario_funcionamento: '05:00 - 00:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '51',
    nome: 'Parque Anhanguera',
    descricao: 'Segundo maior parque urbano de São Paulo.',
    tipo: 'parque',
    latitude: -23.4899,
    longitude: -46.7617,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '52',
    nome: 'Shopping Metrô Tatuapé',
    descricao: 'Shopping integrado à estação de metrô.',
    tipo: 'abrigo',
    latitude: -23.5412,
    longitude: -46.5756,
    horario_funcionamento: '10:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '53',
    nome: 'CEU Paz',
    descricao: 'Centro educacional unificado com biblioteca climatizada.',
    tipo: 'abrigo',
    latitude: -23.4756,
    longitude: -46.6834,
    horario_funcionamento: '07:00 - 22:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '54',
    nome: 'Parque Guarapiranga',
    descricao: 'Parque às margens da represa com áreas sombreadas.',
    tipo: 'parque',
    latitude: -23.6951,
    longitude: -46.7234,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '55',
    nome: 'UBS Dr. José Marcílio Malta Cardoso',
    descricao: 'Unidade básica de saúde climatizada.',
    tipo: 'abrigo',
    latitude: -23.5123,
    longitude: -46.7045,
    horario_funcionamento: '07:00 - 17:00',
    cidade: 'São Paulo',
    uf: 'SP',
  },
  {
    id: '56',
    nome: 'Fonte do Parque Trianon',
    descricao: 'Fonte histórica no coração da Avenida Paulista.',
    tipo: 'fonte',
    latitude: -23.5615,
    longitude: -46.6555,
    horario_funcionamento: '06:00 - 18:00',
    cidade: 'São Paulo',
    uf: 'SP',
  }
];
